from enum import Enum


class PerformanceDomain(str, Enum):
    PORTFOLIO = "PORTFOLIO"
    SLEEVE = "SLEEVE"
    STRATEGY = "STRATEGY"
    SYMBOL = "SYMBOL"


class BenchmarkClass(str, Enum):
    CASH_BASELINE = "CASH_BASELINE"
    BUY_AND_HOLD_SYMBOL = "BUY_AND_HOLD_SYMBOL"
    EQUAL_WEIGHT_SIGNAL_UNIVERSE = "EQUAL_WEIGHT_SIGNAL_UNIVERSE"
    SLEEVE_BASELINE = "SLEEVE_BASELINE"
    REGIME_MATCHED_BASELINE = "REGIME_MATCHED_BASELINE"
    NO_TRADE_BASELINE = "NO_TRADE_BASELINE"
    BASKET_PROXY = "BASKET_PROXY"


class ReturnClass(str, Enum):
    REALIZED_PNL_LINKED = "REALIZED_PNL_LINKED"
    EQUITY_LINKED = "EQUITY_LINKED"
    SLEEVE_RETURN = "SLEEVE_RETURN"
    SYMBOL_RETURN = "SYMBOL_RETURN"


class AttributionClass(str, Enum):
    SIGNAL_SELECTION = "SIGNAL_SELECTION"
    TIMING = "TIMING"
    ALLOCATION_SIZING = "ALLOCATION_SIZING"
    EXECUTION = "EXECUTION"
    FEE_FUNDING_CARRY = "FEE_FUNDING_CARRY"
    RISK_BLOCK_COOLDOWN = "RISK_BLOCK_COOLDOWN"
    RESIDUAL_UNEXPLAINED = "RESIDUAL_UNEXPLAINED"


class DragClass(str, Enum):
    SLIPPAGE = "SLIPPAGE"
    MARKOUT = "MARKOUT"
    FEE = "FEE"
    FUNDING = "FUNDING"
    CARRY = "CARRY"
    TURNOVER = "TURNOVER"
    IDLE_CAPITAL = "IDLE_CAPITAL"


class OpportunityClass(str, Enum):
    CAPTURED = "CAPTURED"
    FOREGONE_SAME_ASSUMPTIONS = "FOREGONE_SAME_ASSUMPTIONS"
    RISK_BLOCKED = "RISK_BLOCKED"
    CAPACITY_CLIPPED = "CAPACITY_CLIPPED"
    UNRESOLVED_COUNTERFACTUAL = "UNRESOLVED_COUNTERFACTUAL"


class CohortClass(str, Enum):
    SYMBOL = "SYMBOL"
    SLEEVE = "SLEEVE"
    STRATEGY = "STRATEGY"
    MODEL = "MODEL"
    FEATURE_FAMILY = "FEATURE_FAMILY"
    REGIME = "REGIME"
    SESSION_WINDOW = "SESSION_WINDOW"


class EquivalenceVerdict(str, Enum):
    EQUIVALENT = "EQUIVALENT"
    MINOR_DIVERGENCE = "MINOR_DIVERGENCE"
    MATERIAL_DIVERGENCE = "MATERIAL_DIVERGENCE"
    NOT_COMPARABLE = "NOT_COMPARABLE"


class TrustVerdict(str, Enum):
    TRUSTED = "TRUSTED"
    CAUTION = "CAUTION"
    DEGRADED = "DEGRADED"
    BLOCKED = "BLOCKED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"


class WindowClass(str, Enum):
    TRADE_LIFECYCLE = "TRADE_LIFECYCLE"
    SESSION = "SESSION"
    DAILY = "DAILY"
    ROLLING = "ROLLING"
    ACTIVATION_STAGE = "ACTIVATION_STAGE"
    EXPERIMENT = "EXPERIMENT"
