from enum import Enum


class IncidentState(str, Enum):
    OPEN = "OPEN"
    ESCALATED = "ESCALATED"
    CONTAINED = "CONTAINED"
    DEGRADED = "DEGRADED"
    RECOVERY_REVIEW = "RECOVERY_REVIEW"
    CLOSED = "CLOSED"
    REOPENED = "REOPENED"


class IncidentSeverity(str, Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    INCIDENT = "INCIDENT"
    MAJOR_INCIDENT = "MAJOR_INCIDENT"
    CRITICAL_INCIDENT = "CRITICAL_INCIDENT"


class IncidentScopeType(str, Enum):
    SYMBOL = "SYMBOL"
    PROFILE = "PROFILE"
    SESSION = "SESSION"
    WORKSPACE = "WORKSPACE"
    GLOBAL = "GLOBAL"


class SignalType(str, Enum):
    MARKET_TRUTH_BROKEN = "MARKET_TRUTH_BROKEN"
    SHADOW_DRIFT_CRITICAL = "SHADOW_DRIFT_CRITICAL"
    LIFECYCLE_UNRESOLVED_SPIKE = "LIFECYCLE_UNRESOLVED_SPIKE"
    CAPITAL_FREEZE_ESCALATED = "CAPITAL_FREEZE_ESCALATED"
    ACTIVATION_PROBATION_FAIL = "ACTIVATION_PROBATION_FAIL"
    CROSS_BOOK_CONFLICT = "CROSS_BOOK_CONFLICT"
    POLICY_HARD_BLOCK = "POLICY_HARD_BLOCK"
    MIGRATION_FAILED = "MIGRATION_FAILED"
    REMEDIATION_FAILED = "REMEDIATION_FAILED"
    UNKNOWN = "UNKNOWN"


class ContainmentIntentType(str, Enum):
    NO_NEW_EXPOSURE = "NO_NEW_EXPOSURE"
    SYMBOL_QUARANTINE = "SYMBOL_QUARANTINE"
    PROFILE_HOLD = "PROFILE_HOLD"
    STAGE_HALT_RECOMMENDED = "STAGE_HALT_RECOMMENDED"
    LIMITED_SESSION_FREEZE = "LIMITED_SESSION_FREEZE"
    CAPITAL_FREEZE_ADVISORY = "CAPITAL_FREEZE_ADVISORY"
    GLOBAL_HALT_ADVISORY = "GLOBAL_HALT_ADVISORY"


class DegradedModeType(str, Enum):
    OBSERVE_ONLY = "OBSERVE_ONLY"
    NO_NEW_EXPOSURE = "NO_NEW_EXPOSURE"
    EXIT_ONLY = "EXIT_ONLY"
    LIMITED_SYMBOLS_ONLY = "LIMITED_SYMBOLS_ONLY"
    PAPER_SHADOW_ONLY = "PAPER_SHADOW_ONLY"
    CAPITAL_CONSTRAINED = "CAPITAL_CONSTRAINED"
    DATA_DEGRADED = "DATA_DEGRADED"


class RecoveryVerdict(str, Enum):
    NOT_READY = "NOT_READY"
    CONDITIONAL = "CONDITIONAL"
    READY = "READY"
    REQUIRES_BOARD_REVIEW = "REQUIRES_BOARD_REVIEW"
