with open("app/main.py", "a") as f:
    f.write("""
    group.add_argument("--show-controlling-factors", action="store_true")
    group.add_argument("--show-precedent-applicability", action="store_true")
    group.add_argument("--show-binding-precedent", action="store_true")
    group.add_argument("--show-persuasive-precedent", action="store_true")
    group.add_argument("--show-analogies", action="store_true")
    group.add_argument("--show-distinctions", action="store_true")
    group.add_argument("--show-carve-outs", action="store_true")
    group.add_argument("--show-precedent-exceptions", action="store_true")
    group.add_argument("--show-precedent-conflicts", action="store_true")
    group.add_argument("--show-precedent-hierarchy", action="store_true")
    group.add_argument("--show-precedent-overrides", action="store_true")
    group.add_argument("--show-precedent-overrules", action="store_true")
    group.add_argument("--show-precedent-supersession", action="store_true")
    group.add_argument("--show-precedent-consistency", action="store_true")
    group.add_argument("--show-precedent-comparisons", action="store_true")
    group.add_argument("--show-precedent-readiness", action="store_true")
    group.add_argument("--show-precedent-forecast", action="store_true")
    group.add_argument("--show-precedent-debt", action="store_true")
    group.add_argument("--show-precedent-equivalence", action="store_true")
    group.add_argument("--show-precedent-trust", action="store_true")
    group.add_argument("--show-precedent-review-packs", action="store_true")
""")
