import os

# Helper script to create files
files_to_touch = [
    "app/change_plane/models.py",
    "app/change_plane/enums.py",
    "app/change_plane/exceptions.py",
    "app/change_plane/base.py",
    "app/change_plane/registry.py",
    "app/change_plane/objects.py",
    "app/change_plane/requests.py",
    "app/change_plane/classifications.py",
    "app/change_plane/impact.py",
    "app/change_plane/blast_radius.py",
    "app/change_plane/approvals.py",
    "app/change_plane/windows.py",
    "app/change_plane/calendars.py",
    "app/change_plane/dependencies.py",
    "app/change_plane/freezes.py",
    "app/change_plane/rollback.py",
    "app/change_plane/rollforward.py",
    "app/change_plane/execution.py",
    "app/change_plane/verification.py",
    "app/change_plane/observations.py",
    "app/change_plane/exceptions_records.py",
    "app/change_plane/collisions.py",
    "app/change_plane/risks.py",
    "app/change_plane/forecasting.py",
    "app/change_plane/debt.py",
    "app/change_plane/readiness.py",
    "app/change_plane/programs.py",
    "app/change_plane/releases.py",
    "app/change_plane/activation.py",
    "app/change_plane/security.py",
    "app/change_plane/continuity.py",
    "app/change_plane/capacity.py",
    "app/change_plane/costs.py",
    "app/change_plane/knowledge.py",
    "app/change_plane/assurance.py",
    "app/change_plane/operating_model.py",
    "app/change_plane/incidents.py",
    "app/change_plane/portfolio.py",
    "app/change_plane/equivalence.py",
    "app/change_plane/divergence.py",
    "app/change_plane/quality.py",
    "app/change_plane/trust.py",
    "app/change_plane/manifests.py",
    "app/change_plane/reporting.py",
    "app/change_plane/storage.py",
    "app/change_plane/repository.py",

    "app/release_plane/readiness.py",
    "app/release_plane/rollouts.py",
    "app/activation/guards.py",
    "app/activation/history.py",
    "app/incident_plane/recovery.py",
    "app/security_plane/readiness.py",
    "app/continuity_plane/readiness.py",
    "app/assurance_plane/releases.py",
    "app/assurance_plane/activation.py",
    "app/operating_model_plane/approvers.py",
    "app/program_plane/replans.py",
    "app/program_plane/dependencies.py",
    "app/portfolio_plane/commitments.py",
    "app/knowledge_plane/runbooks.py",
    "app/compliance_plane/findings.py",
    "app/policy_plane/evaluations.py",
    "app/policy_kernel/context.py",
    "app/policy_kernel/invariants.py",
    "app/readiness_board/evidence.py",
    "app/readiness_board/domains.py",
    "app/reliability/domains.py",
    "app/reliability/slos.py",
    "app/observability_plane/events.py",
    "app/observability_plane/diagnostics.py",
    "app/evidence_graph/artefacts.py",
    "app/evidence_graph/packs.py",
    "app/reviews/requests.py",
    "app/identity/capabilities.py",
    "app/observability/alerts.py",
    "app/observability/runbooks.py",
    "app/telegram/notifier.py",
    "app/telegram/templates.py",

    "tests/test_change_plane_registry.py",
    "tests/test_change_plane_objects.py",
    "tests/test_change_plane_requests.py",
    "tests/test_change_plane_classifications.py",
    "tests/test_change_plane_impact.py",
    "tests/test_change_plane_blast_radius.py",
    "tests/test_change_plane_approvals.py",
    "tests/test_change_plane_windows.py",
    "tests/test_change_plane_calendars.py",
    "tests/test_change_plane_dependencies.py",
    "tests/test_change_plane_freezes.py",
    "tests/test_change_plane_rollback.py",
    "tests/test_change_plane_rollforward.py",
    "tests/test_change_plane_execution.py",
    "tests/test_change_plane_verification.py",
    "tests/test_change_plane_observations.py",
    "tests/test_change_plane_exceptions_records.py",
    "tests/test_change_plane_collisions.py",
    "tests/test_change_plane_risks.py",
    "tests/test_change_plane_forecasting.py",
    "tests/test_change_plane_debt.py",
    "tests/test_change_plane_readiness.py",
    "tests/test_change_plane_programs.py",
    "tests/test_change_plane_releases.py",
    "tests/test_change_plane_activation.py",
    "tests/test_change_plane_security.py",
    "tests/test_change_plane_continuity.py",
    "tests/test_change_plane_capacity.py",
    "tests/test_change_plane_costs.py",
    "tests/test_change_plane_knowledge.py",
    "tests/test_change_plane_assurance.py",
    "tests/test_change_plane_operating_model.py",
    "tests/test_change_plane_incidents.py",
    "tests/test_change_plane_portfolio.py",
    "tests/test_change_plane_equivalence.py",
    "tests/test_change_plane_divergence.py",
    "tests/test_change_plane_quality.py",
    "tests/test_change_plane_trust.py",
    "tests/test_change_plane_manifests.py",
    "tests/test_change_plane_storage.py",

    "docs/489_change_plane_ve_change_intent_change_window_blast_radius_rollback_governance_mimarisi.md",
    "docs/490_standard_normal_emergency_change_approval_window_freeze_politikasi.md",
    "docs/491_post_change_verification_quiet_period_rollback_rollforward_collision_politikasi.md",
    "docs/492_change_integrity_readiness_release_activation_incident_entegrasyonu_politikasi.md",
    "docs/493_phase_96_definition_of_done.md"
]

for f in files_to_touch:
    # touch file if not exist
    if not os.path.exists(f):
        # make dir just in case
        os.makedirs(os.path.dirname(f), exist_ok=True)
        with open(f, 'w') as fh:
            pass
