class AutonomyPlaneError(Exception): pass
class InvalidAutonomyObjectError(AutonomyPlaneError): pass
class InvalidMandateError(AutonomyPlaneError): pass
class InvalidDelegationGrantError(AutonomyPlaneError): pass
class InvalidScopeError(AutonomyPlaneError): pass
class InvalidConfidenceThresholdError(AutonomyPlaneError): pass
class InvalidOverrideError(AutonomyPlaneError): pass
class AutonomyTheaterViolationError(AutonomyPlaneError): pass
class AutonomyStorageError(AutonomyPlaneError): pass
