from enum import Enum


class LifecycleState(str, Enum):
    CREATED = "CREATED"
    READY_TO_SUBMIT = "READY_TO_SUBMIT"
    SUBMITTED_PENDING_ACK = "SUBMITTED_PENDING_ACK"
    ACKNOWLEDGED_OPEN = "ACKNOWLEDGED_OPEN"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    FULLY_FILLED = "FULLY_FILLED"
    CANCEL_REQUESTED = "CANCEL_REQUESTED"
    CANCELLED = "CANCELLED"
    REPLACE_REQUESTED = "REPLACE_REQUESTED"
    REPLACED = "REPLACED"
    REJECTED = "REJECTED"
    TIMEOUT_UNKNOWN = "TIMEOUT_UNKNOWN"
    ORPHANED = "ORPHANED"
    DEAD_LETTERED = "DEAD_LETTERED"


class AttemptStatus(str, Enum):
    ACTIVE = "ACTIVE"
    TERMINAL = "TERMINAL"
    AMBIGUOUS = "AMBIGUOUS"


class TransitionType(str, Enum):
    INITIALIZE = "INITIALIZE"
    SUBMIT = "SUBMIT"
    ACK = "ACK"
    REJECT = "REJECT"
    PARTIAL_FILL = "PARTIAL_FILL"
    FULL_FILL = "FULL_FILL"
    REQUEST_CANCEL = "REQUEST_CANCEL"
    CANCEL_ACK = "CANCEL_ACK"
    CANCEL_REJECT = "CANCEL_REJECT"
    REQUEST_REPLACE = "REQUEST_REPLACE"
    REPLACE_ACK = "REPLACE_ACK"
    REPLACE_REJECT = "REPLACE_REJECT"
    MARK_TIMEOUT = "MARK_TIMEOUT"
    MARK_ORPHAN = "MARK_ORPHAN"
    MARK_DEAD_LETTER = "MARK_DEAD_LETTER"


class CancelVerdict(str, Enum):
    ALLOWED = "ALLOWED"
    FORBIDDEN_TERMINAL = "FORBIDDEN_TERMINAL"
    FORBIDDEN_RACE = "FORBIDDEN_RACE"


class ReplaceVerdict(str, Enum):
    ALLOWED = "ALLOWED"
    FORBIDDEN_REDUCE_ONLY_BREAK = "FORBIDDEN_REDUCE_ONLY_BREAK"
    FORBIDDEN_TERMINAL = "FORBIDDEN_TERMINAL"


class TimeoutClass(str, Enum):
    PENDING_ACK_TIMEOUT = "PENDING_ACK_TIMEOUT"
    CANCEL_TIMEOUT = "CANCEL_TIMEOUT"
    STALE_PARTIAL_FILL = "STALE_PARTIAL_FILL"


class OrphanSeverity(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class DedupVerdict(str, Enum):
    NEW_EVENT = "NEW_EVENT"
    DUPLICATE_EVENT = "DUPLICATE_EVENT"
    CONFLICTING_EVENT = "CONFLICTING_EVENT"


class LifecycleVerdict(str, Enum):
    HEALTHY = "HEALTHY"
    CAUTION = "CAUTION"
    UNRESOLVED = "UNRESOLVED"


class EventSource(str, Enum):
    VENUE_WS = "VENUE_WS"
    VENUE_REST = "VENUE_REST"
    INTERNAL_TIMEOUT = "INTERNAL_TIMEOUT"
    MANUAL_RECONCILE = "MANUAL_RECONCILE"
