from enum import Enum

class ObligationClass(str, Enum):
    CONTRACT_PERFORMANCE = "CONTRACT_PERFORMANCE"
    COMPLIANCE_REPORTING = "COMPLIANCE_REPORTING"
    RIGHTS_NOTICE = "RIGHTS_NOTICE"
    REMEDY_EXECUTION = "REMEDY_EXECUTION"
    FINALITY_REOPEN = "FINALITY_REOPEN"
    SECURITY_RESPONSE = "SECURITY_RESPONSE"
    RELEASE_GATE = "RELEASE_GATE"
    MIGRATION_SUPPORT = "MIGRATION_SUPPORT"
    AUTHORITY_ESCALATION = "AUTHORITY_ESCALATION"
    LIABILITY_MITIGATION = "LIABILITY_MITIGATION"
    FEDERATED_DEPENDENCY = "FEDERATED_DEPENDENCY"
    CROSS_PLANE_MANDATORY = "CROSS_PLANE_MANDATORY"

class DutyClass(str, Enum):
    AFFIRMATIVE = "AFFIRMATIVE"
    NEGATIVE = "NEGATIVE"
    REPORTING = "REPORTING"
    REVIEW = "REVIEW"

class RequirementClass(str, Enum):
    MANDATORY = "MANDATORY"
    CONDITIONAL = "CONDITIONAL"
    CONTINGENT = "CONTINGENT"
    IMPLIED = "IMPLIED"

class ProhibitionClass(str, Enum):
    HARD = "HARD"
    CONDITIONAL = "CONDITIONAL"
    TEMPORARY = "TEMPORARY"
    BENEFICIARY_PROTECTIVE = "BENEFICIARY_PROTECTIVE"

class TriggerClass(str, Enum):
    EVENT = "EVENT"
    STATE = "STATE"
    RIGHTS = "RIGHTS"
    LIABILITY = "LIABILITY"

class DeadlineClass(str, Enum):
    HARD = "HARD"
    SOFT = "SOFT"
    ROLLING = "ROLLING"
    EXTERNAL = "EXTERNAL"

class RecurrenceClass(str, Enum):
    RECURRING = "RECURRING"
    PERIODIC = "PERIODIC"
    EVENT_RECURRING = "EVENT_RECURRING"
    ONCE_ONLY = "ONCE_ONLY"

class BreachClass(str, Enum):
    MISSED = "MISSED"
    LATE = "LATE"
    INCOMPLETE = "INCOMPLETE"
    PROHIBITED_ACTION = "PROHIBITED_ACTION"

class DischargeClass(str, Enum):
    COMPLETED = "COMPLETED"
    BENEFICIARY_SAFE = "BENEFICIARY_SAFE"
    PARTIAL = "PARTIAL"
    DISPUTED = "DISPUTED"

class ExcuseClass(str, Enum):
    JUSTIFIED = "JUSTIFIED"
    INSUFFICIENT = "INSUFFICIENT"
    PARTIAL = "PARTIAL"
    POST_HOC = "POST_HOC"

class ObligationEquivalenceVerdict(str, Enum):
    EQUIVALENT = "EQUIVALENT"
    PARTIAL = "PARTIAL"
    DIVERGENT = "DIVERGENT"

class ObligationTrustVerdict(str, Enum):
    TRUSTED = "TRUSTED"
    CAUTION = "CAUTION"
    DEGRADED = "DEGRADED"
    BLOCKED = "BLOCKED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
