from enum import Enum

class ClearingClass(Enum):
    CCP_TRADE_CLEARING = "CCP_TRADE_CLEARING"
    CLIENT_PORTABILITY_CLEARING = "CLIENT_PORTABILITY_CLEARING"
    COLLATERALIZED_DEFAULT_CLEARING = "COLLATERALIZED_DEFAULT_CLEARING"

class AccountClass(Enum):
    HOUSE = "HOUSE"
    CLIENT_OMNIBUS = "CLIENT_OMNIBUS"
    CLIENT_INDIVIDUAL = "CLIENT_INDIVIDUAL"

class TradeStatus(Enum):
    ACCEPTED = "ACCEPTED"
    PENDING = "PENDING"
    REJECTED = "REJECTED"

class SegregationClass(Enum):
    CLEAN_INDIVIDUAL = "CLEAN_INDIVIDUAL"
    BOUNDED_OMNIBUS = "BOUNDED_OMNIBUS"
    CONTAMINATED = "CONTAMINATED"
    FAKE_SEGREGATION = "FAKE_SEGREGATION"

class MarginClass(Enum):
    SUFFICIENT = "SUFFICIENT"
    THIN = "THIN"
    STRESSED = "STRESSED"
    STALE = "STALE"

class DefaultClass(Enum):
    VALID_DEFAULT = "VALID_DEFAULT"
    TECHNICAL_DEFAULT = "TECHNICAL_DEFAULT"
    CONTESTED_DEFAULT = "CONTESTED_DEFAULT"

class AuctionClass(Enum):
    WELL_FORMED = "WELL_FORMED"
    PARTIAL = "PARTIAL"
    COSMETIC = "COSMETIC"
    FAILED = "FAILED"

class RecoveryClass(Enum):
    CASH_CALL = "CASH_CALL"
    GAINS_HAIRCUT = "GAINS_HAIRCUT"
    TEAR_UP = "TEAR_UP"
    FORCED_LIQUIDATION = "FORCED_LIQUIDATION"

class DebtClass(Enum):
    SEGREGATION_DEBT = "SEGREGATION_DEBT"
    MARGIN_SUFFICIENCY_DEBT = "MARGIN_SUFFICIENCY_DEBT"
    AUCTION_GAP_DEBT = "AUCTION_GAP_DEBT"
    PORTABILITY_DEBT = "PORTABILITY_DEBT"
    LOSS_ALLOCATION_DEBT = "LOSS_ALLOCATION_DEBT"

class EquivalenceVerdict(Enum):
    EQUIVALENT = "EQUIVALENT"
    PARTIAL_DIVERGENCE = "PARTIAL_DIVERGENCE"
    MATERIAL_DIVERGENCE = "MATERIAL_DIVERGENCE"

class TrustVerdict(Enum):
    TRUSTED = "TRUSTED"
    CAUTION = "CAUTION"
    DEGRADED = "DEGRADED"
    BLOCKED = "BLOCKED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
