from enum import Enum

class RecapitalizationClass(str, Enum):
    RESOLUTION_EXIT = "RESOLUTION_EXIT"
    INSOLVENCY_PLAN = "INSOLVENCY_PLAN"
    MINIMUM_CAPITAL_RESTORATION = "MINIMUM_CAPITAL_RESTORATION"
    FEDERATED_RESCUE = "FEDERATED_RESCUE"
    LIABILITY_RESTORATION = "LIABILITY_RESTORATION"

class FundingClass(str, Enum):
    UNFUNDED = "UNFUNDED"
    PARTIALLY_FUNDED = "PARTIALLY_FUNDED"
    FUNDED = "FUNDED"
    FAILED = "FAILED"

class DilutionClass(str, Enum):
    EXPECTED = "EXPECTED"
    PROTECTED = "PROTECTED"
    UNFAIR = "UNFAIR"
    HIDDEN = "HIDDEN"

class TrustVerdict(str, Enum):
    TRUSTED = "TRUSTED"
    CAUTION = "CAUTION"
    DEGRADED = "DEGRADED"
    BLOCKED = "BLOCKED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
