from enum import Enum

class MigrationClass(str, Enum):
    SCHEMA_EVOLUTION = "SCHEMA_EVOLUTION"
    MANIFEST_FORMAT = "MANIFEST_FORMAT"
    RUNTIME_STATE = "RUNTIME_STATE"
    STORAGE_INDEX = "STORAGE_INDEX"
    FEATURE_SHAPE = "FEATURE_SHAPE"
    MODEL_IO_CONTRACT = "MODEL_IO_CONTRACT"
    WORKFLOW_CONTRACT = "WORKFLOW_CONTRACT"
    RELEASE_BUNDLE = "RELEASE_BUNDLE"
    POLICY_RULE = "POLICY_RULE"
    CONTROL_RECEIPT = "CONTROL_RECEIPT"
    HISTORICAL_BACKFILL = "HISTORICAL_BACKFILL"
    DEPRECATION_CLEANUP = "DEPRECATION_CLEANUP"

class TransitionClass(str, Enum):
    FORWARD_ONLY = "FORWARD_ONLY"
    REVERSIBLE = "REVERSIBLE"
    SHADOW_TRANSITION = "SHADOW_TRANSITION"
    DUAL_READ = "DUAL_READ"
    DUAL_WRITE = "DUAL_WRITE"
    CUTOVER_REQUIRED = "CUTOVER_REQUIRED"
    DESTRUCTIVE_TRANSITION = "DESTRUCTIVE_TRANSITION"

class CompatibilityClass(str, Enum):
    FULLY_COMPATIBLE = "FULLY_COMPATIBLE"
    BACKWARD_COMPATIBLE = "BACKWARD_COMPATIBLE"
    FORWARD_COMPATIBLE = "FORWARD_COMPATIBLE"
    INCOMPATIBLE = "INCOMPATIBLE"
    SHIM_REQUIRED = "SHIM_REQUIRED"
    PARTIAL = "PARTIAL"

class PrecheckClass(str, Enum):
    PASSED = "PASSED"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"
    PENDING = "PENDING"
    BLOCKER = "BLOCKER"

class CutoverClass(str, Enum):
    STAGED = "STAGED"
    IMMEDIATE = "IMMEDIATE"
    DOWNTIME_REQUIRED = "DOWNTIME_REQUIRED"
    ZERO_DOWNTIME = "ZERO_DOWNTIME"
    SHADOW = "SHADOW"

class RollbackClass(str, Enum):
    SUPPORTED = "SUPPORTED"
    UNSUPPORTED = "UNSUPPORTED"
    DATA_LOSS_RISK = "DATA_LOSS_RISK"
    PARTIAL = "PARTIAL"
    MANUAL_REQUIRED = "MANUAL_REQUIRED"

class DebtClass(str, Enum):
    SHIM_DEBT = "SHIM_DEBT"
    UNVERIFIED_CUTOVER = "UNVERIFIED_CUTOVER"
    DEFERRED_CLEANUP = "DEFERRED_CLEANUP"
    DUAL_WRITE = "DUAL_WRITE"
    PARTIAL_MIGRATION = "PARTIAL_MIGRATION"

class ShimClass(str, Enum):
    READ_SHIM = "READ_SHIM"
    WRITE_SHIM = "WRITE_SHIM"
    API_SHIM = "API_SHIM"
    STATE_SHIM = "STATE_SHIM"

class EquivalenceVerdict(str, Enum):
    EQUIVALENT = "EQUIVALENT"
    DIVERGED = "DIVERGED"
    PARTIAL_EQUIVALENCE = "PARTIAL_EQUIVALENCE"
    INCOMPARABLE = "INCOMPARABLE"
    UNKNOWN = "UNKNOWN"

class TrustVerdict(str, Enum):
    TRUSTED = "TRUSTED"
    CAUTION = "CAUTION"
    DEGRADED = "DEGRADED"
    BLOCKED = "BLOCKED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
