POSTMORTEM_REQUIRED_TEMPLATE = "Postmortem required for incident {incident_id}"
POSTMORTEM_OVERDUE_TEMPLATE = "Postmortem overdue for incident {incident_id}"
RECURRENCE_RISK_ELEVATED_TEMPLATE = "Recurrence risk elevated for postmortem {postmortem_id}"
CAPA_STALE_TEMPLATE = "CAPA stale for action {action_id}"
POSTMORTEM_FINALIZED_TEMPLATE = "Postmortem finalized for incident {incident_id}"
