from enum import Enum


class ModelDomain(str, Enum):
    STRATEGY = "STRATEGY"
    RISK = "RISK"
    EXECUTION = "EXECUTION"
    MARKET_TRUTH = "MARKET_TRUTH"
    OBSERVABILITY = "OBSERVABILITY"
    DECISION_QUALITY = "DECISION_QUALITY"


class ModelClass(str, Enum):
    REGIME_CLASSIFIER = "REGIME_CLASSIFIER"
    SIGNAL_SCORER = "SIGNAL_SCORER"
    RANKING_MODEL = "RANKING_MODEL"
    CONFIDENCE_ESTIMATOR = "CONFIDENCE_ESTIMATOR"
    ABSTENTION_MODEL = "ABSTENTION_MODEL"
    EXECUTION_QUALITY_PREDICTOR = "EXECUTION_QUALITY_PREDICTOR"
    DECISION_QUALITY_AUX_SCORER = "DECISION_QUALITY_AUX_SCORER"
    VOLATILITY_RISK_PREDICTOR = "VOLATILITY_RISK_PREDICTOR"
    ANOMALY_DETECTOR = "ANOMALY_DETECTOR"
    ENSEMBLE_COMBINER = "ENSEMBLE_COMBINER"


class OutputClass(str, Enum):
    SCALAR_SCORE = "SCALAR_SCORE"
    BINARY_CLASS = "BINARY_CLASS"
    MULTICLASS_REGIME = "MULTICLASS_REGIME"
    PROBABILITY_VECTOR = "PROBABILITY_VECTOR"
    CONFIDENCE_INTERVAL = "CONFIDENCE_INTERVAL"
    ABSTAIN_REJECT = "ABSTAIN_REJECT"


class CalibrationClass(str, Enum):
    WELL_CALIBRATED = "WELL_CALIBRATED"
    UNDER_CONFIDENT = "UNDER_CONFIDENT"
    OVER_CONFIDENT = "OVER_CONFIDENT"
    UNSTABLE = "UNSTABLE"
    UNKNOWN = "UNKNOWN"


class UncertaintyClass(str, Enum):
    HIGH_CONFIDENCE = "HIGH_CONFIDENCE"
    MODERATE_CONFIDENCE = "MODERATE_CONFIDENCE"
    LOW_CONFIDENCE = "LOW_CONFIDENCE"
    UNKNOWN = "UNKNOWN"


class ThresholdClass(str, Enum):
    DECISION = "DECISION"
    NO_TRADE = "NO_TRADE"
    REVIEW_ONLY = "REVIEW_ONLY"


class EnsembleClass(str, Enum):
    WEIGHTED_AVERAGE = "WEIGHTED_AVERAGE"
    MAJOR_DIVERGENCE = "MAJOR_DIVERGENCE"
    MAJORITY_VOTE = "MAJORITY_VOTE"
    GATING = "GATING"
    FALLBACK_ORDERING = "FALLBACK_ORDERING"
    CONDITIONAL_ROUTING = "CONDITIONAL_ROUTING"


class EquivalenceVerdict(str, Enum):
    EQUIVALENT = "EQUIVALENT"
    MINOR_DIVERGENCE = "MINOR_DIVERGENCE"
    MAJOR_DIVERGENCE = "MAJOR_DIVERGENCE"
    UNKNOWN = "UNKNOWN"


class DriftSeverity(str, Enum):
    NONE = "NONE"
    LOW = "LOW"
    MODERATE = "MODERATE"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"
    UNKNOWN = "UNKNOWN"


class TrustedSignalVerdict(str, Enum):
    TRUSTED = "TRUSTED"
    CAUTION = "CAUTION"
    DEGRADED = "DEGRADED"
    BLOCKED = "BLOCKED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
