from enum import Enum


class MigrationDomain(str, Enum):
    CONFIG = "CONFIG"
    WORKSPACE = "WORKSPACE"
    DATA_GOVERNANCE = "DATA_GOVERNANCE"
    UNIVERSE = "UNIVERSE"
    POLICY_KERNEL = "POLICY_KERNEL"
    LEDGER_METADATA = "LEDGER_METADATA"
    SHADOW_STATE = "SHADOW_STATE"
    QUALIFICATION = "QUALIFICATION"
    KNOWLEDGE_CATALOG = "KNOWLEDGE_CATALOG"
    REMEDIATION = "REMEDIATION"
    RELEASE_MANIFEST = "RELEASE_MANIFEST"


class MigrationType(str, Enum):
    SCHEMA_CHANGE = "SCHEMA_CHANGE"
    DATA_TRANSFORMATION = "DATA_TRANSFORMATION"
    METADATA_ENRICHMENT = "METADATA_ENRICHMENT"
    KEY_RENAME = "KEY_RENAME"
    NAMESPACE_SPLIT = "NAMESPACE_SPLIT"


class ApplyClass(str, Enum):
    LOCAL_METADATA = "LOCAL_METADATA"
    LOCAL_DATA = "LOCAL_DATA"
    VENUE_ADJACENT = "VENUE_ADJACENT"
    DESTRUCTIVE = "DESTRUCTIVE"


class CompatibilityVerdict(str, Enum):
    SAFE = "SAFE"
    SAFE_WITH_CAUTION = "SAFE_WITH_CAUTION"
    INCOMPATIBLE = "INCOMPATIBLE"


class ReversibilityClass(str, Enum):
    REVERSIBLE = "REVERSIBLE"
    PARTIALLY_REVERSIBLE = "PARTIALLY_REVERSIBLE"
    NON_REVERSIBLE = "NON_REVERSIBLE"


class MigrationSeverity(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class PreflightVerdict(str, Enum):
    PASS = "PASS"
    WARN = "WARN"
    BLOCK = "BLOCK"


class MigrationStatus(str, Enum):
    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    APPLIED_CLEAN = "APPLIED_CLEAN"
    APPLIED_WITH_CAUTION = "APPLIED_WITH_CAUTION"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    SKIPPED = "SKIPPED"
    QUARANTINED = "QUARANTINED"
    ROLLED_BACK = "ROLLED_BACK"


class RollbackStrategy(str, Enum):
    AUTOMATIC = "AUTOMATIC"
    MANUAL_SCRIPT = "MANUAL_SCRIPT"
    NOT_SUPPORTED = "NOT_SUPPORTED"


class MigrationVerdict(str, Enum):
    SUCCESS = "SUCCESS"
    FAILURE = "FAILURE"
    PARTIAL = "PARTIAL"
    PENDING_REVIEW = "PENDING_REVIEW"
