from enum import Enum

class NettingClass(str, Enum):
    ESCROW_RELEASE_NETTING = "ESCROW_RELEASE_NETTING"
    WATERFALL_DISTRIBUTION_NETTING = "WATERFALL_DISTRIBUTION_NETTING"
    COLLATERAL_LIQUIDATION_NETTING = "COLLATERAL_LIQUIDATION_NETTING"
    INSURANCE_CLAIM_NETTING = "INSURANCE_CLAIM_NETTING"
    INDEMNITY_REIMBURSEMENT_NETTING = "INDEMNITY_REIMBURSEMENT_NETTING"
    REMEDY_AWARD_NETTING = "REMEDY_AWARD_NETTING"
    SUCCESSOR_BALANCE_NETTING = "SUCCESSOR_BALANCE_NETTING"
    SUNSET_TAIL_NETTING = "SUNSET_TAIL_NETTING"
    FEDERATED_COUNTERPARTY_NETTING = "FEDERATED_COUNTERPARTY_NETTING"
    CROSS_PLANE_CLOSEOUT_NETTING = "CROSS_PLANE_CLOSEOUT_NETTING"

class ObligationClass(str, Enum):
    PAYABLE = "PAYABLE"
    RECEIVABLE = "RECEIVABLE"
    SHADOW = "SHADOW"
    INELIGIBLE = "INELIGIBLE"

class MutualityClass(str, Enum):
    CLEAN_MUTUALITY = "CLEAN_MUTUALITY"
    PARTIAL_MUTUALITY = "PARTIAL_MUTUALITY"
    FAILED_MUTUALITY = "FAILED_MUTUALITY"
    FAKE_MUTUALITY = "FAKE_MUTUALITY"

class ValuationClass(str, Enum):
    FRESH_VALUATION = "FRESH_VALUATION"
    AGING_VALUATION = "AGING_VALUATION"
    STALE_VALUATION = "STALE_VALUATION"
    MANIPULATED_VALUATION = "MANIPULATED_VALUATION"

class SetoffClass(str, Enum):
    VALID_SETOFF_RIGHT = "VALID_SETOFF_RIGHT"
    CONDITIONAL_SETOFF_RIGHT = "CONDITIONAL_SETOFF_RIGHT"
    BLOCKED_SETOFF_RIGHT = "BLOCKED_SETOFF_RIGHT"
    OVERCLAIMED_SETOFF_RIGHT = "OVERCLAIMED_SETOFF_RIGHT"

class CloseoutClass(str, Enum):
    PRUDENT_CLOSEOUT = "PRUDENT_CLOSEOUT"
    PARTIAL_CLOSEOUT = "PARTIAL_CLOSEOUT"
    CHERRY_PICKED_CLOSEOUT = "CHERRY_PICKED_CLOSEOUT"
    HIDDEN_CLOSEOUT_ASYMMETRY = "HIDDEN_CLOSEOUT_ASYMMETRY"

class ResidualClass(str, Enum):
    CASH_RESIDUAL = "CASH_RESIDUAL"
    CLAIM_RESIDUAL = "CLAIM_RESIDUAL"
    DISPUTED_RESIDUAL = "DISPUTED_RESIDUAL"
    HIDDEN_RESIDUAL_EXPOSURE = "HIDDEN_RESIDUAL_EXPOSURE"

class DebtClass(str, Enum):
    STALE_VALUATION_DEBT = "STALE_VALUATION_DEBT"
    MUTUALITY_DEBT = "MUTUALITY_DEBT"
    STAY_IGNORE_DEBT = "STAY_IGNORE_DEBT"
    RESIDUAL_BURIAL_DEBT = "RESIDUAL_BURIAL_DEBT"
    DOUBLE_OFFSET_DEBT = "DOUBLE_OFFSET_DEBT"

class EquivalenceVerdict(str, Enum):
    FULLY_EQUIVALENT = "FULLY_EQUIVALENT"
    PARTIALLY_EQUIVALENT = "PARTIALLY_EQUIVALENT"
    DIVERGENT = "DIVERGENT"

class TrustVerdict(str, Enum):
    TRUSTED = "TRUSTED"
    CAUTION = "CAUTION"
    DEGRADED = "DEGRADED"
    BLOCKED = "BLOCKED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
