
from enum import Enum

class WaterfallClass(str, Enum):
    COLLATERAL_REALIZATION = "COLLATERAL_REALIZATION"
    INSURANCE_PAYOUT = "INSURANCE_PAYOUT"
    INDEMNITY_RECOVERY = "INDEMNITY_RECOVERY"
    REMEDIAL_AWARD = "REMEDIAL_AWARD"
    SUCCESSOR_RESIDUE = "SUCCESSOR_RESIDUE"
    SUNSET_TAIL = "SUNSET_TAIL"
    FEDERATED_PROCEEDS = "FEDERATED_PROCEEDS"
    CROSS_PLANE_DISTRIBUTION = "CROSS_PLANE_DISTRIBUTION"

class ClaimClass(str, Enum):
    DIRECT_PAYABLE = "DIRECT_PAYABLE"
    DISPUTED = "DISPUTED"
    CONTINGENT = "CONTINGENT"
    UNSUPPORTED = "UNSUPPORTED"

class RankClass(str, Enum):
    VALID = "VALID"
    CONDITIONAL = "CONDITIONAL"
    STALE = "STALE"
    MANIPULATED = "MANIPULATED"

class PoolClass(str, Enum):
    DISTRIBUTABLE = "DISTRIBUTABLE"
    MIXED = "MIXED"
    RESTRICTED = "RESTRICTED"
    PHANTOM = "PHANTOM"

class ReserveClass(str, Enum):
    PRUDENT = "PRUDENT"
    THIN = "THIN"
    COSMETIC = "COSMETIC"
    GAP = "GAP"

class DistributionClass(str, Enum):
    VALID = "VALID"
    PARTIAL = "PARTIAL"
    BLOCKED = "BLOCKED"
    AUTHORITY_DEFECTIVE = "AUTHORITY_DEFECTIVE"

class ClawbackClass(str, Enum):
    VALID = "VALID"
    PARTIAL = "PARTIAL"
    DENIED = "DENIED"
    COSMETIC = "COSMETIC"

class DebtClass(str, Enum):
    STALE_RANK = "STALE_RANK"
    RESERVE_COSMETICS = "RESERVE_COSMETICS"
    LEAKAGE = "LEAKAGE"
    DISPUTED_CLAIM = "DISPUTED_CLAIM"
    CLAWBACK = "CLAWBACK"

class EquivalenceVerdict(str, Enum):
    EQUIVALENT = "EQUIVALENT"
    DIVERGENT = "DIVERGENT"
    PARTIAL = "PARTIAL"

class TrustVerdict(str, Enum):
    TRUSTED = "TRUSTED"
    CAUTION = "CAUTION"
    DEGRADED = "DEGRADED"
    BLOCKED = "BLOCKED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
