class PolicyInvariants:
    NO_ACTIVATION_WITH_UNRESOLVED_CRITICAL_CONFIG_DRIFT = True
    NO_RUNTIME_SAFE_PATCH_OUTSIDE_ALLOWED_MUTABILITY_CLASS = True
    NO_TRUSTED_RUNTIME_POSTURE_UNDER_BROKEN_CONFIG_EQUIVALENCE = True
    NO_HIDDEN_DEFAULT_ON_HIGH_RISK_CONFIG_SURFACES = True
