from enum import Enum

class ExceptionClass(Enum):
    POLICY_WAIVER = "POLICY_WAIVER"
    SECURITY_DEROGATION = "SECURITY_DEROGATION"
    AUTONOMY_CONTROLLED = "AUTONOMY_CONTROLLED"
    ORCHESTRATION_EMERGENCY = "ORCHESTRATION_EMERGENCY"
    BENEFICIARY_PROTECTION = "BENEFICIARY_PROTECTION"
    COMPLIANCE_DEROGATION = "COMPLIANCE_DEROGATION"
    MIGRATION_BRIDGE = "MIGRATION_BRIDGE"
    SUSPENSION_RESIDUAL = "SUSPENSION_RESIDUAL"
    RENEWAL_GAP = "RENEWAL_GAP"
    FEDERATED_CONTRACT = "FEDERATED_CONTRACT"
    EVIDENCE_GAP_TEMPORARY = "EVIDENCE_GAP_TEMPORARY"
    CROSS_PLANE_BOUNDED_DEVIATION = "CROSS_PLANE_BOUNDED_DEVIATION"

class TrustVerdictEnum(Enum):
    TRUSTED = "TRUSTED"
    CAUTION = "CAUTION"
    DEGRADED = "DEGRADED"
    BLOCKED = "BLOCKED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"

class DebtClass(Enum):
    SERIAL_WAIVER = "SERIAL_WAIVER"
    STALE_EXCEPTION = "STALE_EXCEPTION"
    CONTROL_THEATER = "CONTROL_THEATER"
    PRECEDENT = "PRECEDENT"
    BACKDOOR = "BACKDOOR"
