from enum import Enum

class EnforcementClass(str, Enum):
    INTERVENTION = "INTERVENTION"
    HOLD = "HOLD"
    BLOCK = "BLOCK"
    QUARANTINE = "QUARANTINE"
    SUSPENSION = "SUSPENSION"
    DISABLEMENT = "DISABLEMENT"
    KILL_SWITCH = "KILL_SWITCH"
    ROLLBACK = "ROLLBACK"
    REVERSAL = "REVERSAL"
    SANCTION = "SANCTION"
    RATE_LIMIT = "RATE_LIMIT"
    GATE = "GATE"
    COMPENSATING_RESTRICTION = "COMPENSATING_RESTRICTION"

class InterventionClass(str, Enum):
    PREVENTIVE = "PREVENTIVE"
    CORRECTIVE = "CORRECTIVE"
    CONTAINMENT = "CONTAINMENT"
    COERCIVE = "COERCIVE"

class SanctionClass(str, Enum):
    FORMAL = "FORMAL"
    PROVISIONAL = "PROVISIONAL"
    BEHAVIOR = "BEHAVIOR"
    PARTNER = "PARTNER"

class RestrictionClass(str, Enum):
    TEMPORARY = "TEMPORARY"
    SCOPED = "SCOPED"
    BENEFICIARY_PROTECTIVE = "BENEFICIARY_PROTECTIVE"

class TriggerClass(str, Enum):
    OBLIGATION = "OBLIGATION"
    RIGHTS = "RIGHTS"
    LIABILITY = "LIABILITY"
    RISK = "RISK"

class ReversibilityClass(str, Enum):
    FULLY_REVERSIBLE = "FULLY_REVERSIBLE"
    PARTIALLY_REVERSIBLE = "PARTIALLY_REVERSIBLE"
    IRREVERSIBLE = "IRREVERSIBLE"
    CONDITIONAL = "CONDITIONAL"

class AppealClass(str, Enum):
    APPEALABLE = "APPEALABLE"
    NON_APPEALABLE_EMERGENCY = "NON_APPEALABLE_EMERGENCY"
    AUTOMATIC_REVIEW = "AUTOMATIC_REVIEW"
    DUE_PROCESS_BYPASSED = "DUE_PROCESS_BYPASSED"

class LiftClass(str, Enum):
    EXPLICIT = "EXPLICIT"
    PARTIAL = "PARTIAL"
    BLOCKED = "BLOCKED"
    PREMATURE = "PREMATURE"

class DueProcessClass(str, Enum):
    PRE_REVIEWED = "PRE_REVIEWED"
    POST_REVIEW_REQUIRED = "POST_REVIEW_REQUIRED"
    EMERGENCY_BYPASS = "EMERGENCY_BYPASS"

class ProportionalityClass(str, Enum):
    PROPORTIONATE = "PROPORTIONATE"
    UNDER_ENFORCEMENT = "UNDER_ENFORCEMENT"
    OVER_ENFORCEMENT = "OVER_ENFORCEMENT"
    DISCRIMINATORY = "DISCRIMINATORY"

class EquivalenceVerdict(str, Enum):
    EQUIVALENT = "EQUIVALENT"
    DIVERGENT = "DIVERGENT"

class TrustVerdictClass(str, Enum):
    TRUSTED = "TRUSTED"
    CAUTION = "CAUTION"
    DEGRADED = "DEGRADED"
    BLOCKED = "BLOCKED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
